### ISSUE TITLE
#dont_allow / #dont_allow! : make other tests fail

### ISSUE THREAD

**Issue by daipom** [rr/rr#102]
`#dont_allow / #dont_allow!` API can make other tests fail.
It appears that the tests using `ObjectSpace` fail because of the APIs.

# How to reproduce

This is based on the test script that @Watson1978 made.
(https://github.com/fluent/fluentd/issues/4063).

```rb
require 'bundler/inline'
gemfile do
  source 'https://rubygems.org'
  gem 'rr'
  gem 'test-unit'
  gem 'test-unit-rr'
end

class SampleTest < ::Test::Unit::TestCase
  def test_a
    dont_allow!.foo
  end

  def test_b
    ObjectSpace.each_object do |obj|
      obj.class
    end
  end
end
```

```console
$ ruby test.rb
Loaded suite test
Started
F
====================================================================================================================================================================
Failure: test_b(SampleTest):
  Called 1 time.
  Expected 0 times.
test.rb:16:in `block in test_b'
     13: 
     14:   def test_b
     15:     ObjectSpace.each_object do |obj|
  => 16:       obj.class
     17:     end
     18:   end
     19: end
test.rb:15:in `each_object'
test.rb:15:in `test_b'
====================================================================================================================================================================
Finished in 0.003105795 seconds.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
2 tests, 0 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
50% passed
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
643.96 tests/s, 0.00 assertions/s
```

# Envirionment

* ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
* rr (3.1.1)
* test-unit-rr (1.0.5)
* test-unit (3.6.2)

**Comment by daipom** [comment]
The same object is referred to.
However, their contents differ.
The object referred to in `test_b` does not have `foo` method.
Is the object left halfway?

```rb
require 'bundler/inline'
gemfile do
  source 'https://rubygems.org'
  gem 'rr'
  gem 'test-unit'
  gem 'test-unit-rr'
end

class SampleTest < ::Test::Unit::TestCase
  def test_a
    o = dont_allow!.foo.subject
    p o
    p o.method(:foo)
  end

  def test_b
    ObjectSpace.each_object do |obj|
      obj.class
    rescue => e
      p e
      p obj
      p obj.method(:foo)
    end
  end
end
```

```console
$ ruby test.rb
Loaded suite test
Started
#<Object:0x00007fe62a63bfb0>
#<Method: #<Object:0x00007fe62a63bfb0>.foo(*args, &block) /home/daipom/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rr-3.1.1/lib/rr/injections/double_injection.rb:141>
|#<RR::Errors::TimesCalledError:"Called 1 time.\nExpected 0 times.">
#<Object:0x00007fe62a63bfb0>
E
====================================================================================================================================================================
Error: test_b(SampleTest): NameError: undefined method `foo' for class `#<Class:#<Object:0x00007fe62a63bfb0>>'
test.rb:22:in `method'
test.rb:22:in `rescue in block in test_b'
test.rb:18:in `block in test_b'
     15: 
     16:   def test_b
     17:     ObjectSpace.each_object do |obj|
  => 18:       obj.class
     19:     rescue => e
     20:       p e
     21:       p obj
test.rb:17:in `each_object'
test.rb:17:in `test_b'
====================================================================================================================================================================
Finished in 0.003156916 seconds.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
2 tests, 0 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
50% passed
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
633.53 tests/s, 0.00 assertions/s
```

**Comment by kou** [comment]
We don't need multiple tests:

```ruby
require "test/unit/rr"

class SampleTest < ::Test::Unit::TestCase
  def test_a
    dont_allow!.foo
    ObjectSpace.each_object do |obj|
      obj.class
    end
  end
end
```

I call `dont_allow!` object as A and its subject (`dont_allow!.foo.subject`) as B here.

This is caused by:

1. `ObjectSpace.each_object` iterates A and then B.
2. `A.class` is called when A is iterated. It disallows `B.class`.
3. `B.class` is called and rejected when B is iterated.

Solutions:

1. Use `mock.foo.never` to disallow only `foo`

   ```ruby
   require "test/unit/rr"

   class SampleTest < ::Test::Unit::TestCase
     def test_a
       mock!.foo.never
       ObjectSpace.each_object do |obj|
         obj.class
       end
     end
   end
   ```

2. Accept `A.class`:

   ```ruby
   require "test/unit/rr"

   class SampleTest < ::Test::Unit::TestCase
     def test_a
       double = dont_allow!
       double.foo
       def double.class
         Kernel.instance_method(:class).bind_call(self)
       end
       ObjectSpace.each_object do |obj|
         obj.class
       end
     end
   end
   ```

**Comment by kou** [comment]
Ah, `1.` may not be a solution. `B.class` in `ObjectSpace.each_object` returns `nil`.

**Comment by daipom** [comment]
> I call `dont_allow!` object as A and its subject (`dont_allow!.foo.subject`) as B here.
> 
> This is caused by:
> 
>     1. `ObjectSpace.each_object` iterates A and then B.
>     2. `A.class` is called when A is iterated. It disallows `B.class`.
>     3. `B.class` is called and rejected when B is iterated.

I see! Thanks for your explanation!
So, it is the correct behavior.

> Solutions:
> 1. Use `mock.foo.never` to disallow only `foo`
> 2. Accept `A.class`:
>
> Ah, `1.` may not be a solution. `B.class` in `ObjectSpace.each_object` returns `nil`.

I'm not clear on this.
We assume that `1.`  would be a solution in https://github.com/fluent/fluentd/issues/4063.

Why does `B.class` return `nil`?
The following script outputs `Object` correctly as the class of B.

```rb
require "test/unit/rr"

class SampleTest < ::Test::Unit::TestCase
  def test_a
    o = mock!.foo.never.subject
    ObjectSpace.each_object do |obj|
      p obj.class if o.equal? obj
    end
  end
end
```

**Comment by kou** [comment]
`A.class` creates a `B.class` method that returns `nil`:

```ruby
require "test/unit/rr"

class SampleTest < ::Test::Unit::TestCase
  def test_a
    double = mock!
    subject = double.foo.never.subject
    p subject.class # => Object
    double.class
    p subject.class # => nil
  end
end
```

**Comment by daipom** [comment]
Oh... I see. Thanks for your explanation!

The script on https://github.com/rr/rr/issues/102#issuecomment-2421359173 is not suitable.
I have confirmed it becomes `nil` by the following script.

```rb
require "test/unit/rr"

class SampleTest < ::Test::Unit::TestCase
  def test_a
    o = mock!.foo.never.subject
    ObjectSpace.each_object do |obj|
      if o.equal? obj
        p obj.class # => nil
      else
        obj.class
      end
    end
  end
end
```

**Comment by daipom** [comment]
Thanks!
So, we have two solutions for `ObjectSpace.each_object`.

https://github.com/rr/rr/issues/102#issuecomment-2421126247
> Solutions:
> 1. Use `mock.foo.never` to disallow only `foo`
> 2. Accept `A.class`:

However, `1.` is not a perfect solution.
It can avoid unexpected failure, but it can still affect its subject unexpectedly.

To avoid these effects perfectly, we need `2.`.

**Comment by daipom** [comment]
@kou Thanks for your quick and kind response!
