### ISSUE TITLE
verifying mock argument loosely?

### ISSUE THREAD

**Issue by uu59** [rr/rr#61]
Verifying mock arguments looks too loose.

```ruby
require "test-unit"
require "test/unit/rr"

class FooTest < Test::Unit::TestCase
  def test_nil
    d = Object.new
    mock(d).foo([:a])

    d.foo([:a, nil, nil])
  end

  def test_extra
    d = Object.new
    mock(d).foo([:a])

    d.foo([:a, :b])
  end

  def test_hash
    d = Object.new
    mock(d).foo({})

    d.foo({a: 1, b: 3})
  end
end

puts "test-unit: #{Test::Unit::VERSION}"
puts "test-unit-rr: #{Test::Unit::RR::VERSION}"
puts "rr: #{RR::VERSION}"
```

```console
$ ruby /tmp/foo.rb
test-unit: 3.1.4
test-unit-rr: 1.0.3
rr: 1.1.2
Loaded suite /tmp/foo
Started
...

Finished in 0.004627 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
3 tests, 0 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
648.37 tests/s, 0.00 assertions/s
```

I'm not sure this is expected behavior or not.
And if expected, how do I verify argument strictly?

**Comment by kou** [comment]
Thanks for your report.
All cases are failed at master:

```text
% ruby -I ../test-unit/lib -I ../test-unit-rr/lib -I ../rr/lib /tmp/a.rb  
--------------------------------------------------------------------------------
Warning from RR:
  RR::Adapters::RRMethods is deprecated;
  please use RR::DSL instead.

Called from:
 - /home/kou/work/ruby/test-unit-rr/lib/test/unit/rr.rb:24:in `include'
 - /home/kou/work/ruby/test-unit-rr/lib/test/unit/rr.rb:24:in `<module:Adapter>'
 - /home/kou/work/ruby/test-unit-rr/lib/test/unit/rr.rb:23:in `<module:RR>'
--------------------------------------------------------------------------------
test-unit: 3.1.6
test-unit-rr: 1.0.4
rr: 1.2.0
Loaded suite /tmp/a
Started
F
================================================================================
Failure:
  On subject #<Object:0x00000001706b28>,
  unexpected method invocation:
    foo([:a, :b])
  expected invocations:
  - foo([:a])
test_extra(FooTest)
/home/kou/work/ruby/rr/lib/rr/method_dispatches/base_method_dispatch.rb:76:in `double_not_found_error'
/home/kou/work/ruby/rr/lib/rr/method_dispatches/method_missing_dispatch.rb:27:in `call'
/home/kou/work/ruby/rr/lib/rr/injections/method_missing_injection.rb:77:in `method_missing'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:134:in `foo'
/tmp/a.rb:16:in `test_extra'
     13:     d = Object.new
     14:     mock(d).foo([:a])
     15: 
  => 16:     d.foo([:a, :b])
     17:   end
     18: 
     19:   def test_hash
================================================================================
F
================================================================================
Failure:
  foo([:a])
  Called 0 times.
  Expected 1 times.
test_extra(FooTest)
/home/kou/work/ruby/rr/lib/rr/expectations/times_called_expectation.rb:29:in `verify!'
/home/kou/work/ruby/rr/lib/rr/double.rb:57:in `verify'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:158:in `block in verify'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:157:in `each'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:157:in `verify'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:71:in `verify_double'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:63:in `block (2 levels) in verify'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:62:in `each'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:62:in `block in verify'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:60:in `each'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:60:in `verify'
/home/kou/work/ruby/rr/lib/rr/space.rb:56:in `verify_doubles'
/home/kou/work/ruby/rr/lib/rr/without_autohook.rb:115:in `verify'
/home/kou/work/ruby/rr/lib/rr/integrations/test_unit_1.rb:38:in `teardown_with_rr'
================================================================================
F
================================================================================
Failure:
  On subject #<Object:0x000000016ab408>,
  unexpected method invocation:
    foo({:a=>1, :b=>3})
  expected invocations:
  - foo({})
test_hash(FooTest)
/home/kou/work/ruby/rr/lib/rr/method_dispatches/base_method_dispatch.rb:76:in `double_not_found_error'
/home/kou/work/ruby/rr/lib/rr/method_dispatches/method_missing_dispatch.rb:27:in `call'
/home/kou/work/ruby/rr/lib/rr/injections/method_missing_injection.rb:77:in `method_missing'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:134:in `foo'
/tmp/a.rb:23:in `test_hash'
     20:     d = Object.new
     21:     mock(d).foo({})
     22: 
  => 23:     d.foo({a: 1, b: 3})
     24:   end
     25: end
     26: 
================================================================================
F
================================================================================
Failure:
  foo({})
  Called 0 times.
  Expected 1 times.
test_hash(FooTest)
/home/kou/work/ruby/rr/lib/rr/expectations/times_called_expectation.rb:29:in `verify!'
/home/kou/work/ruby/rr/lib/rr/double.rb:57:in `verify'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:158:in `block in verify'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:157:in `each'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:157:in `verify'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:71:in `verify_double'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:63:in `block (2 levels) in verify'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:62:in `each'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:62:in `block in verify'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:60:in `each'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:60:in `verify'
/home/kou/work/ruby/rr/lib/rr/space.rb:56:in `verify_doubles'
/home/kou/work/ruby/rr/lib/rr/without_autohook.rb:115:in `verify'
/home/kou/work/ruby/rr/lib/rr/integrations/test_unit_1.rb:38:in `teardown_with_rr'
================================================================================
F
================================================================================
Failure:
  On subject #<Object:0x00000001617230>,
  unexpected method invocation:
    foo([:a, nil, nil])
  expected invocations:
  - foo([:a])
test_nil(FooTest)
/home/kou/work/ruby/rr/lib/rr/method_dispatches/base_method_dispatch.rb:76:in `double_not_found_error'
/home/kou/work/ruby/rr/lib/rr/method_dispatches/method_missing_dispatch.rb:27:in `call'
/home/kou/work/ruby/rr/lib/rr/injections/method_missing_injection.rb:77:in `method_missing'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:134:in `foo'
/tmp/a.rb:9:in `test_nil'
      6:     d = Object.new
      7:     mock(d).foo([:a])
      8: 
  =>  9:     d.foo([:a, nil, nil])
     10:   end
     11: 
     12:   def test_extra
================================================================================
F
================================================================================
Failure:
  foo([:a])
  Called 0 times.
  Expected 1 times.
test_nil(FooTest)
/home/kou/work/ruby/rr/lib/rr/expectations/times_called_expectation.rb:29:in `verify!'
/home/kou/work/ruby/rr/lib/rr/double.rb:57:in `verify'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:158:in `block in verify'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:157:in `each'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:157:in `verify'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:71:in `verify_double'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:63:in `block (2 levels) in verify'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:62:in `each'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:62:in `block in verify'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:60:in `each'
/home/kou/work/ruby/rr/lib/rr/injections/double_injection.rb:60:in `verify'
/home/kou/work/ruby/rr/lib/rr/space.rb:56:in `verify_doubles'
/home/kou/work/ruby/rr/lib/rr/without_autohook.rb:115:in `verify'
/home/kou/work/ruby/rr/lib/rr/integrations/test_unit_1.rb:38:in `teardown_with_rr'
================================================================================


Finished in 0.018214578 seconds.
--------------------------------------------------------------------------------
3 tests, 0 assertions, 6 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
--------------------------------------------------------------------------------
164.70 tests/s, 0.00 assertions/s
```

It seems that we should release a new version.

(We should remove needless backtrace.)
