### ISSUE TITLE
Keyword argument assertion results differ between Ruby 2.x and Ruby 3.x

### ISSUE THREAD

**Issue by daipom** [rr/rr#96]
Keyword argument assertion results differ between Ruby 2.x and Ruby 3.x.
Is this an intentional change?

I found a similar issue to this in `rspec`: 

* https://github.com/rspec/rspec-mocks/issues/1460

How to reproduce:

* OS: Ubuntu 20.04 LTS

* `test.rb`

```ruby
require "rr"

class TestClass
  def testMethod(a, b = {})
  end
end

testClass = TestClass.new
RR::mock(testClass).testMethod("hoge", fuga: "fuga", foo: "foo").times(2)

options = {
  fuga: "fuga",
  foo: "foo",
}
testClass.testMethod("hoge", fuga: "fuga", foo: "foo")
testClass.testMethod("hoge", options)

p "Success!!"
```

* Ruby 2.7.5

```console
$ rbenv local 2.7.5
$ rbenv version
2.7.5 (set by ...)
$ gem info rr
...
rr (3.0.9)
...
$ ruby test.rb
"Success!!"
```

* Ruby 3.0.3

```console
$ rbenv local 3.0.3
$ rbenv version
3.0.3 (set by ...)
$ gem info rr
...
rr (3.1.0)
...
$ ruby test.rb
/home/daipom/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rr-3.1.0/lib/rr/method_dispatches/base_method_dispatch.rb:93:in `double_not_found_error': On subject #<TestClass:0x000055e81e8e0858>, (RR::Errors::DoubleNotFoundError)
unexpected method invocation:
  testMethod("hoge", {:fuga=>"fuga", :foo=>"foo"})
expected invocations:
- testMethod("hoge", fuga: "fuga", foo: "foo")
	from /home/daipom/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rr-3.1.0/lib/rr/method_dispatches/method_dispatch.rb:28:in `call'
	from /home/daipom/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rr-3.1.0/lib/rr/injections/double_injection.rb:226:in `dispatch_method'
	from /home/daipom/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rr-3.1.0/lib/rr/injections/double_injection.rb:45:in `dispatch_method'
	from /home/daipom/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rr-3.1.0/lib/rr/injections/double_injection.rb:161:in `testMethod'
	from test-rr.rb:16:in `<main>'
```

* Ruby 3.1.0

```console
$ rbenv local 3.1.0
$ rbenv version
3.1.0 (set by ...)
$ gem info rr
...
rr (3.1.0)
...
$ ruby test.rb
/home/daipom/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rr-3.1.0/lib/rr/method_dispatches/base_method_dispatch.rb:93:in `double_not_found_error': On subject #<TestClass:0x00007f74c3bb4448>, (RR::Errors::DoubleNotFoundError)
unexpected method invocation:
  testMethod("hoge", {:fuga=>"fuga", :foo=>"foo"})
expected invocations:
- testMethod("hoge", fuga: "fuga", foo: "foo")
	from /home/daipom/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rr-3.1.0/lib/rr/method_dispatches/method_dispatch.rb:28:in `call'
	from /home/daipom/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rr-3.1.0/lib/rr/injections/double_injection.rb:226:in `dispatch_method'
	from /home/daipom/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rr-3.1.0/lib/rr/injections/double_injection.rb:45:in `dispatch_method'
	from /home/daipom/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rr-3.1.0/lib/rr/injections/double_injection.rb:161:in `testMethod'
	from test-rr.rb:16:in `<main>'
```

**Comment by daipom** [comment]
Sorry, this seems to be caused by the following Ruby update:

* https://www.ruby-lang.org/ja/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

So this may be the intended behavior.
I close this.

**Comment by kou** [comment]
This should work.

**Comment by kou** [comment]
Ah, no. The following should work:

```ruby
require "rr"

class TestClass
end

testClass = TestClass.new
RR::mock(testClass).testMethod("hoge", {fuga: "fuga", foo: "foo"}).times(2)

options = {
  fuga: "fuga",
  foo: "foo",
}
testClass.testMethod("hoge", {fuga: "fuga", foo: "foo"})
testClass.testMethod("hoge", options)

p "Success!!"
```

**Comment by kou** [comment]
Ah, the following should work:

```ruby
require "rr"

class TestClass
end

testClass = TestClass.new
RR::mock(testClass).testMethod("hoge", {fuga: "fuga", foo: "foo"}).times(2)

options = {
  fuga: "fuga",
  foo: "foo",
}
testClass.testMethod("hoge", {fuga: "fuga", foo: "foo"})
testClass.testMethod("hoge", options)
testClass.testMethod("hoge", fuga: "fuga", foo: "foo")

p "Success!!"
```

**Comment by daipom** [comment]
Thanks for your reply!

`times(2)` should be `times(3)`.

Yes! I think this should work.

* https://docs.ruby-lang.org/en/3.1/Hash.html
  > when the last argument in a method call is a Hash, the curly braces may be omitted
